# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 07:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('edrpou', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('company_hash', models.TextField(primary_key=True, serialize=False, verbose_name='Ключ дедуплікації')),
                ('name', models.TextField(verbose_name='Назва компанії')),
                ('short_name', models.TextField(verbose_name='Скорочена назва компанії')),
                ('location', models.TextField(verbose_name='Адреса реєстрації')),
                ('company_profile', models.TextField(verbose_name='Основний вид діяльності')),
                ('status', models.IntegerField(choices=[(0, 'інформація відсутня'), (1, 'зареєстровано'), (2, 'припинено'), (3, 'в стані припинення'), (4, 'зареєстровано, свідоцтво про державну реєстрацію недійсне'), (5, 'порушено справу про банкрутство'), (6, 'порушено справу про банкрутство (санація)'), (7, 'розпорядження майном'), (8, 'ліквідація')])),
                ('revisions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('head', 'Голова'), ('founder', 'Засновник'), ('owner', 'Бенефіціарний власник')], max_length=10)),
                ('name', models.TextField()),
                ('revisions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRecord',
            fields=[
                ('person_hash', models.TextField(primary_key=True, serialize=False, verbose_name='Ключ дедуплікації')),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('raw_record', models.TextField()),
                ('tokenized_record', models.TextField()),
                ('share', models.TextField()),
                ('revisions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('revision_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер ревізії')),
                ('dataset_id', models.TextField(verbose_name='Датасет')),
                ('created', models.DateTimeField(verbose_name='Дата створення')),
                ('url', models.URLField(verbose_name='Посилання на набір данних')),
            ],
        ),
    ]
