# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180210_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecord',
            name='company_profile',
            field=models.TextField(blank=True, verbose_name='Основний вид діяльності'),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='location',
            field=models.TextField(blank=True, verbose_name='Адреса реєстрації'),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='short_name',
            field=models.TextField(blank=True, verbose_name='Скорочена назва компанії'),
        ),
    ]
