# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 15:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180210_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecord',
            name='revisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='revisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='personrecord',
            name='revisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterIndexTogether(
            name='companyrecord',
            index_together=set([('company', 'company_hash')]),
        ),
    ]
