# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20180210_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Імпорт завершено'),
        ),
    ]
