# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_revision_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personrecord',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_hash',
            field=models.TextField(default='stupid django', primary_key=True, serialize=False, verbose_name='Ключ дедуплікації'),
        ),
        migrations.AddField(
            model_name='person',
            name='raw_record',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='share',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tokenized_record',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PersonRecord',
        ),
    ]
