# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-15 17:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180218_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecord',
            name='revisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='Ревізії'),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='status',
            field=models.IntegerField(choices=[(0, 'інформація відсутня'), (1, 'зареєстровано'), (2, 'припинено'), (3, 'в стані припинення'), (4, 'зареєстровано, свідоцтво про державну реєстрацію недійсне'), (5, 'порушено справу про банкрутство'), (6, 'порушено справу про банкрутство (санація)'), (7, 'розпорядження майном'), (8, 'ліквідація')], verbose_name='Статус компанії'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None, verbose_name='Адреси'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Компанія'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None, verbose_name='Країни'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None, verbose_name='Імена'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_hash',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Ключ дедуплікації'),
        ),
        migrations.AlterField(
            model_name='person',
            name='raw_record',
            field=models.TextField(blank=True, verbose_name='Оригінал запису'),
        ),
        migrations.AlterField(
            model_name='person',
            name='revisions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='Ревізії'),
        ),
        migrations.AlterField(
            model_name='person',
            name='share',
            field=models.TextField(blank=True, verbose_name='Уставний внесок'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tokenized_record',
            field=models.TextField(blank=True, verbose_name='Токенізований запис'),
        ),
    ]
