# Generated by Django 2.0.4 on 2018-05-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180415_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='ignore',
            field=models.BooleanField(default=False, verbose_name='Ігнорувати через помилки імпорту'),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='companies.Company', verbose_name='Компанія'),
        ),
    ]
