# Generated by Django 2.0.4 on 2018-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20180513_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='location_apartment',
            field=models.CharField(default='', max_length=100, verbose_name='Квартира/офіс/кімната'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='location_locality',
            field=models.CharField(default='', max_length=100, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='location_parsing_quality',
            field=models.FloatField(default=0, verbose_name='Якість парсингу адреси'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='location_postal_code',
            field=models.CharField(default='', max_length=40, verbose_name='Індекс'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='location_region',
            field=models.CharField(default='', max_length=100, verbose_name='Регіон'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='location_street_address',
            field=models.CharField(default='', max_length=200, verbose_name='Вулиця/дім'),
        ),
    ]
