# Generated by Django 2.0.4 on 2018-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20180520_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='location_district',
            field=models.CharField(default='', max_length=100, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='companyrecord',
            name='location_locality',
            field=models.CharField(default='', max_length=100, verbose_name='Місто'),
        ),
    ]
