# Generated by Django 2.0.4 on 2018-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20180520_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='validated_location_apartment',
            field=models.CharField(default='', max_length=100, verbose_name='Валідована Квартира/офіс/кімната'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='validated_location_district',
            field=models.CharField(default='', max_length=100, verbose_name='Валідований Район'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='validated_location_locality',
            field=models.CharField(default='', max_length=100, verbose_name='Валідоване Місто'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='validated_location_postal_code',
            field=models.CharField(default='', max_length=40, verbose_name='Валідований Індекс'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='validated_location_region',
            field=models.CharField(default='', max_length=100, verbose_name='Валідований Регіон'),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='validated_location_street_address',
            field=models.CharField(default='', max_length=200, verbose_name='Валідована Вулиця/дім'),
        ),
    ]
