# Generated by Django 2.0.4 on 2018-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180527_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_dirty',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Потребує повторної індексації'),
        ),
    ]
