# Generated by Django 2.0.7 on 2019-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='revision_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер ревізії'),
        ),
    ]
