# Generated by Django 2.0.7 on 2019-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20190105_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='subrevision_id',
            field=models.CharField(default='', max_length=20, verbose_name='Дурна ревізія з нового сайту data.gov.ua'),
        ),
    ]
