# Generated by Django 2.0.7 on 2019-01-06 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_revision_subrevision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None, verbose_name='Адреси'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None, verbose_name='Країни'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None, verbose_name='Імена'),
        ),
    ]
