# Generated by Django 2.1.7 on 2019-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_companysnapshotflags'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='acting_and_explicitly_stated_that_has_no_bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_bo_on_occupied_soild',
            field=models.BooleanField(default=False),
        ),
    ]
