# Generated by Django 2.1.7 on 2019-06-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_companysnapshotflags_not_present_in_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysnapshotflags',
            old_name='has_very_similar_as_bo_and_head',
            new_name='has_very_similar_person_as_bo_and_head',
        ),
    ]
