# Generated by Django 2.1.7 on 2019-06-08 09:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20190607_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_bo_in_crimea',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companysnapshotflags',
            name='all_similar_founders_and_bos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Результати порівняння бенефіціарів та власників'),
        ),
        migrations.AlterField(
            model_name='companysnapshotflags',
            name='all_similar_heads_and_bos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Результати порівняння бенефіціарів та директорів'),
        ),
    ]
