# Generated by Django 2.1.7 on 2019-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_auto_20190608_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bo_is_absent',
            field=models.BooleanField(default=False, verbose_name='В реєстрі було прямо вказано, що бенефіціар відсутній'),
        ),
    ]
