# Generated by Django 2.1.7 on 2019-06-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20190611_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecord',
            name='shortened_validated_location',
            field=models.TextField(blank=True, db_index=True, verbose_name='Адреса реєстрації (після верифікації за реєстром та без району)'),
        ),
    ]
