# Generated by Django 2.1.7 on 2019-06-13 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_companysnapshotflags_has_mass_registration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='bo_diff',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Зміни в БО'),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_changes_in_bo',
            field=models.BooleanField(default=False),
        ),
    ]
