# Generated by Django 2.2.2 on 2019-06-16 22:26

from django.db import migrations
from tqdm import tqdm


def cleanup_names(apps, schema_editor):
    Person = apps.get_model("companies", "Person")
    qs = Person.objects.exclude(name__len=0).nocache()

    for rec in tqdm(qs.iterator(), total=qs.count()):
        rec.name = list(set(map(str.strip, rec.name)))
        rec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20190616_1133'),
    ]

    operations = [
        migrations.RunPython(cleanup_names, reverse_code=migrations.RunPython.noop)
    ]
