# Generated by Django 2.2.2 on 2019-06-17 09:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_auto_20190616_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='all_founder_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None, verbose_name="Усі країни окрім України, до яких прив'язані засновники"),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='all_similar_heads_and_founders',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Результати порівняння директорів за засновників'),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_same_person_as_head_and_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_very_similar_person_as_head_and_founder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companysnapshotflags',
            name='all_similar_founders_and_bos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name='Результати порівняння бенефіціарів та засновників'),
        ),
    ]
