# Generated by Django 2.2.2 on 2019-06-17 19:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20190617_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_changes_in_ownership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='ownership_diff',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Зміни в власності'),
        ),
    ]
