# Generated by Django 2.2.2 on 2019-06-27 12:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_auto_20190617_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEPOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='Роки в котрих декларувалася інформація про БО')),
                ('person', models.CharField(max_length=100, verbose_name='Особа ПЕП')),
                ('person_url', models.URLField(max_length=100, verbose_name='Посилання на pep.org.ua')),
                ('from_declaration', models.BooleanField(default=False, verbose_name="Зв'язок утворений з інформації з декларації")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peps', to='companies.Company', verbose_name='Компанія')),
            ],
        ),
    ]
