# Generated by Django 2.2.2 on 2019-06-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_pepowners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PEPOwners',
            new_name='PEPOwner',
        ),
    ]
