# Generated by Django 2.2.2 on 2019-06-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_auto_20190628_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_owned', to='companies.Company', verbose_name='Компанія')),
            ],
        ),
    ]
