# Generated by Django 2.2.2 on 2019-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_selfowned'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='indirectly_self_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='self_owned',
            field=models.BooleanField(default=False),
        ),
    ]
