# Generated by Django 2.2.2 on 2019-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0039_auto_20190628_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='charter_capital',
            field=models.FloatField(default=None, null=True),
        ),
    ]
