# Generated by Django 2.2.3 on 2019-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_companysnapshotflags_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='reg_date',
            field=models.DateField(null=True),
        ),
    ]
