# Generated by Django 2.2.3 on 2019-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_companysnapshotflags_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_foreign_bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_foreign_founders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_founders_in_crimea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_founders_on_occupied_soil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_russian_bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_russian_founders',
            field=models.BooleanField(default=False),
        ),
    ]
