# Generated by Django 2.2.3 on 2019-09-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0044_auto_20190915_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='had_pep_founder_in_the_past',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysnapshotflags',
            name='has_pep_founder',
            field=models.BooleanField(default=False),
        ),
    ]
