# Generated by Django 2.2.3 on 2019-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0045_auto_20190915_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepowner',
            name='person_type',
            field=models.CharField(choices=[('head', 'Голова'), ('founder', 'Засновник'), ('owner', 'Бенефіціарний власник')], db_index=True, default='owner', max_length=10),
        ),
    ]
