# Generated by Django 2.2.3 on 2019-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_pepowner_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='charter_capital',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='reg_date',
            field=models.DateField(null=True),
        ),
    ]
