# Generated by Django 2.2.3 on 2019-09-18 08:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_auto_20190917_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysnapshotflags',
            name='bo_changes_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None, verbose_name='Дати зміни БО'),
        ),
    ]
