# Generated by Django 2.2.3 on 2019-11-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_companysnapshotflags_bo_changes_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='form',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
