# Generated by Django 2.2.3 on 2019-11-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_companyrecord_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecord',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='fax',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='phone1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyrecord',
            name='phone2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
